/**
 * url 原先的旧的url
 * newurl 需要被替换url
 * path 接口的路径
 * name 接口的名称
 */
var apis = [
    {url:"appcfg.host.controlV1+'dtt/queryShareCredit.json'",
     newurl:"appcfg.host+'/v1/api/app/dtt/queryShareCredit.json'",
     path:"/v1/api/app/dtt/queryShareCredit.json",
     protocol:"https",
     name:"DTT_QUERYSHARECREDIT.JSON"
    },

    {url:"appcfg.host.controlV1+'shortMessage/shareBrief.json'",
     newurl:"appcfg.host+'/v1/api/app/shortMessage/shareBrief.json'",
     path:"/v1/api/app/shortMessage/shareBrief.json",
    protocol:"https",
     name:"SHORTMESSAGE_SHAREBRIEF.JSON"
    },

    {url:"appcfg.host.controlV1+'dtt/shareFriends.json'",
     newurl:"appcfg.host+'/v1/api/app/dtt/shareFriends.json'",
     path:"/v1/api/app/dtt/shareFriends.json",
    protocol:"https",
     name:"DTT_SHAREFRIENDS.JSON"
    },

    {url:"appcfg.host.controlV1+'dtt/queryDttRule.json'",
     newurl:"appcfg.host+'/v1/api/app/dtt/queryDttRule.json'",
     path:"/v1/api/app/dtt/queryDttRule.json",
    protocol:"https",
     name:"DTT_QUERYDTTRULE.JSON"
    },

    {url:"appcfg.host.controlV1+'dtt/queryUseCredit.json'",
     newurl:"appcfg.host+'/v1/api/app/dtt/queryUseCredit.json'",
     path:"/v1/api/app/dtt/queryUseCredit.json",
    protocol:"https",
     name:"DTT_QUERYUSECREDIT.JSON"
    },

    {url:"appcfg.host.controlV1+'dtt/queryDttHistory.json'",
     newurl:"appcfg.host+'/v1/api/app/dtt/queryDttHistory.json'",
     path:"/v1/api/app/dtt/queryDttHistory.json",
    protocol:"https",
     name:"DTT_QUERYDTTHISTORY.JSON"
    },

    {url:"appcfg.host.controlV1+'dtt/profile.json'",
     newurl:"appcfg.host+'/v1/api/app/dtt/profile.json'",
     path:"/v1/api/app/dtt/profile.json",
    protocol:"https",
     name:"DTT_PROFILE.JSON"
    },

    {url:"appcfg.host.controlV1+'dtt/signIn.json'",
     newurl:"appcfg.host+'/v1/api/app/dtt/signIn.json'",
     path:"/v1/api/app/dtt/signIn.json",
    protocol:"https",
     name:"DTT_SIGNIN.JSON"
    },

    {url:"appcfg.host.controlV1+'news/addNewsReadCredit.json'",
     newurl:"appcfg.host+'/v1/api/app/news/addNewsReadCredit.json'",
     path:"/v1/api/app/news/addNewsReadCredit.json",
    protocol:"https",
     name:"NEWS_ADDNEWSREADCREDIT.JSON"
    },

    {url:"appcfg.host.controlV1+'news/shareNews.json'",
     newurl:"appcfg.host+'/v1/api/app/news/shareNews.json'",
     path:"/v1/api/app/news/shareNews.json",
    protocol:"https",
     name:"NEWS_SHARENEWS.JSON"
    },

    {url:"appcfg.host.controlV1+'tp/loginByEmail.json'",
     newurl:"appcfg.host+'/v1/api/app/tp/loginByEmail.json'",
     path:"/v1/api/app/tp/loginByEmail.json",
    protocol:"https",
     name:"TP_LOGINBYEMAIL.JSON"
    },

    {url:"appcfg.host.controlV1+'tp/activeEmail.json'",
     newurl:"appcfg.host+'/v1/api/app/tp/activeEmail.json'",
     path:"/v1/api/app/tp/activeEmail.json",
    protocol:"https",
     name:"TP_ACTIVEEMAIL.JSON"
    },

    {url:"appcfg.host.controlV1+'tp/registerByEmail.json'",
     newurl:"appcfg.host+'/v1/api/app/tp/registerByEmail.json'",
     path:"/v1/api/app/tp/registerByEmail.json",
    protocol:"https",
     name:"TP_REGISTERBYEMAIL.JSON"
    },

    {url:"appcfg.host.controlV1+'tp/sendResetPwdEmail.json'",
     newurl:"appcfg.host+'/v1/api/app/tp/sendResetPwdEmail.json'",
     path:"/v1/api/app/tp/sendResetPwdEmail.json",
    protocol:"https",
     name:"TP_SENDRESETPWDEMAIL.JSON"
    },

    {url:"appcfg.host.controlV1+'tp/unbindByThirdparty.json'",
     newurl:"appcfg.host+'/v1/api/app/tp/unbindByThirdparty.json'",
     path:"/v1/api/app/tp/unbindByThirdparty.json",
    protocol:"https",
     name:"TP_UNBINDBYTHIRDPARTY.JSON"
    },

    {url:"appcfg.host.controlV1+'register/login.json'",
     newurl:"appcfg.host+'/v1/api/app/register/login.json'",
     path:"/v1/api/app/register/login.json",
    protocol:"https",
     name:"REGISTER_LOGIN.JSON"
    },

    {url:"appcfg.host.controlV1+'user/getUserInfo.json'",
     newurl:"appcfg.host+'/v1/api/app/user/getUserInfo.json'",
     path:"/v1/api/app/user/getUserInfo.json",
    protocol:"https",
     name:"USER_GETUSERINFO.JSON"
    },
    {url:"appcfg.host.controlV1+'dtt/newRuleCount.json'",
     newurl:"appcfg.host+'/v1/api/app/dtt/newRuleCount.json'",
     path:"/v1/api/app/dtt/newRuleCount.json",
    protocol:"https",
     name:"DTT_NEWRULECOUNT.JSON"
    },

    {url:"appcfg.host.controlV1+'dtt/queryDttBanner.json'",
     newurl:"appcfg.host+'/v1/api/app/dtt/queryDttBanner.json'",
     path:"/v1/api/app/dtt/queryDttBanner.json",
    protocol:"https",
     name:"DTT_QUERYDTTBANNER.JSON"
    },

    {url:"appcfg.host.controlV1+'tp/loginOut.json'",
     newurl:"appcfg.host+'/v1/api/app/tp/loginOut.json'",
     path:"/v1/api/app/tp/loginOut.json",
    protocol:"https",
     name:"TP_LOGINOUT.JSON"
    },

    {url:"appcfg.host.controlV1+'wiki/wikiList.json'",
     newurl:"appcfg.host+'/v1/api/app/wiki/wikiList.json'",
     path:"/v1/api/app/wiki/wikiList.json",
    protocol:"https",
     name:"WIKI_WIKILIST.JSON"
    },

    {url:"appcfg.host.controlV1+'wiki/wikiIndex.json'",
     newurl:"appcfg.host+'/v1/api/app/wiki/wikiIndex.json'",
     path:"/v1/api/app/wiki/wikiIndex.json",
    protocol:"https",
     name:"WIKI_WIKIINDEX.JSON"
    },

   {url:"appcfg.host.control+'bcmPortfolio/add.json'",
    newurl:"appcfg.host+'/v1/api/app/bcmPortfolio/add.json'",
    path:"/v1/api/app/bcmPortfolio/add.json",
    protocol:"https",
    name:"BCMPORTFOLIO_ADD.JSON"
   },
   {url:"appcfg.host.control+'bcmAssetCurrency/add.json'",
    newurl:"appcfg.host+'/v1/api/app/bcmAssetCurrency/add.json'",
    path:"/v1/api/app/bcmAssetCurrency/add.json",
    protocol:"https",
    name:"BCMASSETCURRENCY_ADD.JSON"
   },
   {url:"appcfg.host.control+'bcmAssetCurrency/currencyUnitList.json'",
    newurl:"appcfg.host+'/v1/api/app/bcmAssetCurrency/currencyUnitList.json'",
    path:"/v1/api/app/bcmAssetCurrency/currencyUnitList.json",
    protocol:"https",
    name:"BCMASSETCURRENCY_CURRENCYUNITLIST.JSON"
   },
   {url:"appcfg.host.control+'shortMessage/thumbsUp.json'",
    newurl:"appcfg.host+'/v1/api/app/shortMessage/thumbsUp.json'",
    path:"/v1/api/app/shortMessage/thumbsUp.json",
    protocol:"https",
    name:"SHORTMESSAGE_THUMBSUP.JSON"
   },
   {url:"appcfg.host.control+'shortMessage/list.json'",
    newurl:"appcfg.host+'/v1/api/app/shortMessage/list.json'",
    path:"/v1/api/app/shortMessage/list.json",
    protocol:"https",
    name:"SHORTMESSAGE_LIST.JSON"
   },
   {url:"appcfg.host.control+'currency/getCurrencyDeail.json'",
    newurl:"appcfg.host+'/v1/api/app/currency/getCurrencyDeail.json'",
    path:"/v1/api/app/currency/getCurrencyDeail.json",
    protocol:"https",
    name:"CURRENCY_GETCURRENCYDEAIL.JSON"
   },
   {url:"appcfg.host.control+'currency/saveOrCancelCollect.json'",
    newurl:"appcfg.host+'/v1/api/app/currency/saveOrCancelCollect.json'",
    path:"/v1/api/app/currency/saveOrCancelCollect.json",
    protocol:"https",
    name:"CURRENCY_SAVEORCANCELCOLLECT.JSON"
   },
   {url:"appcfg.host.control+'bcmAssetCurrency/delete.json'",
    newurl:"appcfg.host+'/v1/api/app/bcmAssetCurrency/delete.json'",
    path:"/v1/api/app/bcmAssetCurrency/delete.json",
    protocol:"https",
    name:"BCMASSETCURRENCY_DELETE.JSON"
   },
   {url:"appcfg.host.control+'eventTrack/sendTrackNews.json'",
    newurl:"appcfg.host+'/v1/api/app/eventTrack/sendTrackNews.json'",
    path:"/v1/api/app/eventTrack/sendTrackNews.json",
    protocol:"https",
    name:"EVENTTRACK_SENDTRACKNEWS.JSON"
   },
   {url:"appcfg.host.control+'news/queryDetails.json'",
    newurl:"appcfg.host+'/v1/api/app/news/queryDetails.json'",
    path:"/v1/api/app/news/queryDetails.json",
    protocol:"https",
    name:"NEWS_QUERYDETAILS.JSON"
   },
   {url:"appcfg.host.control+'bcmAssetCurrency/view.json'",
    newurl:"appcfg.host+'/v1/api/app/bcmAssetCurrency/view.json'",
    path:"/v1/api/app/bcmAssetCurrency/view.json",
    protocol:"https",
    name:"BCMASSETCURRENCY_VIEW.JSON"
   },
   {url:"appcfg.host.control+'bcmAssetCurrency/update.json'",
    newurl:"appcfg.host+'/v1/api/app/bcmAssetCurrency/update.json'",
    path:"/v1/api/app/bcmAssetCurrency/update.json",
    protocol:"https",
    name:"BCMASSETCURRENCY_UPDATE.JSON"
   },
   {url:"appcfg.host.control+'bcmAssetCurrency/searchCurrency.json'",
    newurl:"appcfg.host+'/v1/api/app/bcmAssetCurrency/searchCurrency.json'",
    path:"/v1/api/app/bcmAssetCurrency/searchCurrency.json",
    protocol:"https",
    name:"BCMASSETCURRENCY_SEARCHCURRENCY.JSON"
   },
   {url:"appcfg.host.control+'bcmAssetCurrency/recommendCurrencyList.json'",
    newurl:"appcfg.host+'/v1/api/app/bcmAssetCurrency/recommendCurrencyList.json'",
    path:"/v1/api/app/bcmAssetCurrency/recommendCurrencyList.json",
    protocol:"https",
    name:"BCMASSETCURRENCY_RECOMMENDCURRENCYLIST.JSON"
   },
   {url:"appcfg.host.control+'bcmAssetCurrency/searchExchange.json'",
    newurl:"appcfg.host+'/v1/api/app/bcmAssetCurrency/searchExchange.json'",
    path:"/v1/api/app/bcmAssetCurrency/searchExchange.json",
    protocol:"https",
    name:"BCMASSETCURRENCY_SEARCHEXCHANGE.JSON"
   },
   {url:"appcfg.host.control+'bcmAssetCurrency/recommendExchangeList.json'",
    newurl:"appcfg.host+'/v1/api/app/bcmAssetCurrency/recommendExchangeList.json'",
    path:"/v1/api/app/bcmAssetCurrency/recommendExchangeList.json",
    protocol:"https",
    name:"BCMASSETCURRENCY_RECOMMENDEXCHANGELIST.JSON"
   },
   {url:"appcfg.host.control+'user/queryUserFavorites.json'",
    newurl:"appcfg.host+'/v1/api/app/user/queryUserFavorites.json'",
    path:"/v1/api/app/user/queryUserFavorites.json",
    protocol:"https",
    name:"USER_QUERYUSERFAVORITES.JSON"
   },
   {url:"appcfg.host.control+'user/deleteUserFavorites.json'",
    newurl:"appcfg.host+'/v1/api/app/user/deleteUserFavorites.json'",
    path:"/v1/api/app/user/deleteUserFavorites.json",
    protocol:"https",
    name:"USER_DELETEUSERFAVORITES.JSON"
   },
   {url:"appcfg.host.control+'user/queryReadHistory.json'",
    newurl:"appcfg.host+'/v1/api/app/user/queryReadHistory.json'",
    path:"/v1/api/app/user/queryReadHistory.json",
    protocol:"https",
    name:"USER_QUERYREADHISTORY.JSON"
   },
   {url:"appcfg.host.control+'user/deleteUserReadHistory.json'",
    newurl:"appcfg.host+'/v1/api/app/user/deleteUserReadHistory.json'",
    path:"/v1/api/app/user/deleteUserReadHistory.json",
    protocol:"https",
    name:"USER_DELETEUSERREADHISTORY.JSON"
   },
   {url:"appcfg.host.control+'user/getUserInfo.json'",
    newurl:"appcfg.host+'/v1/api/app/user/getUserInfo.json'",
    path:"/v1/api/app/user/getUserInfo.json",
    protocol:"https",
    name:"USER_GETUSERINFO.JSON"
   },
   {url:"appcfg.host.control+'eventTrack/sendTrackUser.json'",
    newurl:"appcfg.host+'/v1/api/app/eventTrack/sendTrackUser.json'",
    path:"/v1/api/app/eventTrack/sendTrackUser.json",
    protocol:"https",
    name:"EVENTTRACK_SENDTRACKUSER.JSON"
   },
   {url:"appcfg.host.control+'user/queryWapVersion.json'",
    newurl:"appcfg.host+'/v1/api/app/user/queryWapVersion.json'",
    path:"/v1/api/app/user/queryWapVersion.json",
    protocol:"https",
    name:"USER_QUERYWAPVERSION.JSON"
   },
   {url:"appcfg.host.control+'register/getcode.json'",
    newurl:"appcfg.host+'/v1/api/app/register/getcode.json'",
    path:"/v1/api/app/register/getcode.json",
    protocol:"https",
    name:"REGISTER_GETCODE.JSON"
   },
   {url:"appcfg.host.control+'currency/list.json'",
    newurl:"appcfg.host+'/v1/api/app/currency/list.json'",
    path:"/v1/api/app/currency/list.json",
    protocol:"https",
    name:"CURRENCY_LIST.JSON"
   },
   {url:"appcfg.host.control+'currency/addCollects.json'",
    newurl:"appcfg.host+'/v1/api/app/currency/addCollects.json'",
    path:"/v1/api/app/currency/addCollects.json",
    protocol:"https",
    name:"CURRENCY_ADDCOLLECTS.JSON"
   },
   {url:"appcfg.host.control+'currency/getCollect.json'",
    newurl:"appcfg.host+'/v1/api/app/currency/getCollect.json'",
    path:"/v1/api/app/currency/getCollect.json",
    protocol:"https",
    name:"CURRENCY_GETCOLLECT.JSON"
   },
   {url:"appcfg.host.control+'user/saveUserReadHistory.json'",
    newurl:"appcfg.host+'/v1/api/app/user/saveUserReadHistory.json'",
    path:"/v1/api/app/user/saveUserReadHistory.json",
    protocol:"https",
    name:"USER_SAVEUSERREADHISTORY.JSON"
   },
   {url:"appcfg.host.control+'slide/list.json'",
    newurl:"appcfg.host+'/v1/api/app/slide/list.json'",
    path:"/v1/api/app/slide/list.json",
    protocol:"https",
    name:"SLIDE_LIST.JSON"
   },
   {url:"appcfg.host.control+'eventTrack/sendTrackSliding.json'",
    newurl:"appcfg.host+'/v1/api/app/eventTrack/sendTrackSliding.json'",
    path:"/v1/api/app/eventTrack/sendTrackSliding.json",
    protocol:"https",
    name:"EVENTTRACK_SENDTRACKSLIDING.JSON"
   },
   {url:"appcfg.host.control+'eventTrack/sendTrackDaily.json'",
    newurl:"appcfg.host+'/v1/api/app/eventTrack/sendTrackDaily.json'",
    path:"/v1/api/app/eventTrack/sendTrackDaily.json",
    protocol:"https",
    name:"EVENTTRACK_SENDTRACKDAILY.JSON"
   },
   {url:"appcfg.host.control+'news/list.json'",
    newurl:"appcfg.host+'/v1/api/app/news/list.json'",
    path:"/v1/api/app/news/list.json",
    protocol:"https",
    name:"NEWS_LIST.JSON"
   },
   {url:"appcfg.host.control+'eventTrack/sendTrackChannel.json'",
    newurl:"appcfg.host+'/v1/api/app/eventTrack/sendTrackChannel.json'",
    path:"/v1/api/app/eventTrack/sendTrackChannel.json",
    protocol:"https",
    name:"EVENTTRACK_SENDTRACKCHANNEL.JSON"
   },
   {url:"appcfg.host.control+'register/login.json'",
    newurl:"appcfg.host+'/v1/api/app/register/login.json'",
    path:"/v1/api/app/register/login.json",
    protocol:"https",
    name:"REGISTER_LOGIN.JSON"
   },
   {url:"appcfg.host.control+'bcmPortfolio/list.json'",
    newurl:"appcfg.host+'/v1/api/app/bcmPortfolio/list.json'",
    path:"/v1/api/app/bcmPortfolio/list.json",
    protocol:"https",
    name:"BCMPORTFOLIO_LIST.JSON"
   },
   {url:"appcfg.host.control+'bcmPortfolio/delete.json'",
    newurl:"appcfg.host+'/v1/api/app/bcmPortfolio/delete.json'",
    path:"/v1/api/app/bcmPortfolio/delete.json",
    protocol:"https",
    name:"BCMPORTFOLIO_DELETE.JSON"
   },
   {url:"appcfg.host.control+'bcmPortfolio/update.json'",
    newurl:"appcfg.host+'/v1/api/app/bcmPortfolio/update.json'",
    path:"/v1/api/app/bcmPortfolio/update.json",
    protocol:"https",
    name:"BCMPORTFOLIO_UPDATE.JSON"
   },
   {url:"appcfg.host.control+'channel/list.json'",
    newurl:"appcfg.host+'/v1/api/app/channel/list.json'",
    path:"/v1/api/app/channel/list.json",
    protocol:"https",
    name:"CHANNEL_LIST.JSON"
   },
   {url:"appcfg.host.control+'user/updateUser.json'",
    newurl:"appcfg.host+'/v1/api/app/user/updateUser.json'",
    path:"/v1/api/app/user/updateUser.json",
    protocol:"https",
    name:"USER_UPDATEUSER.JSON"
   },
   {url:"appcfg.host.control+'user/uploadPic.json'",
    newurl:"appcfg.host+'/v1/api/app/user/uploadPic.json'",
    path:"/v1/api/app/user/uploadPic.json",
    protocol:"https",
    name:"USER_UPLOADPIC.JSON"
   },
   {url:"appcfg.host.control+'user/queryAppVersion.json'",
    newurl:"appcfg.host+'/v1/api/app/user/queryAppVersion.json'",
    path:"/v1/api/app/user/queryAppVersion.json",
    protocol:"https",
    name:"USER_QUERYAPPVERSION.JSON"
   },
   {url:"appcfg.host.control+'register/getCountryCode.json'",
    newurl:"appcfg.host+'/v1/api/app/register/getCountryCode.json'",
    path:"/v1/api/app/register/getCountryCode.json",
    protocol:"https",
    name:"REGISTER_GETCOUNTRYCODE.JSON"
   },
   {url:"appcfg.host.control+'news/wikiList.json'",
    newurl:"appcfg.host+'/v1/api/app/news/wikiList.json'",
    path:"/v1/api/app/news/wikiList.json",
    protocol:"https",
    name:"NEWS_WIKILIST.JSON"
   },
   {url:"appcfg.host.control+'daily/list.json'",
    newurl:"appcfg.host+'/v1/api/app/daily/list.json'",
    path:"/v1/api/app/daily/list.json",
    protocol:"https",
    name:"DAILY_LIST.JSON"
   },
   {url:"appcfg.host.control+'news/wikiIndex.json'",
    newurl:"appcfg.host+'/v1/api/app/news/wikiIndex.json'",
    path:"/v1/api/app/news/wikiIndex.json",
    protocol:"https",
    name:"NEWS_WIKIINDEX.JSON"
   },
    {
    url:"appcfg.host.control+'user/saveUserFavorites.json'",
    newurl:"appcfg.host+'/v1/api/app/user/saveUserFavorites.json'",
    path:"v1/api/app/user/saveUserFavorites.json",
    protocol:"https",
    name:"SAVEUSERFAVORITES.JSON"
    },
    {
    url:"appcfg.host.control+'user/saveUserFeedback.json'",
    newurl:"appcfg.host+'/v1/api/app/user/saveUserFeedback.json'",
    path:"v1/api/app/user/saveUserFeedback.json",
    protocol:"https",
    name:"SAVEUSERFEEDBACK.JSON"
    },
    {
    url:"appcfg.host.control+'twitter/queryTwitter.json'",
    newurl:"appcfg.host+'/v1/api/app/twitter/queryTwitter.json'",
    path:"v1/api/app/twitter/queryTwitter.json",
    protocol:"https",
    name:"QUERYTWITTER.JSON"
    },


]
module.exports=apis
